const routesAdmin = {
    qlhs: '/quan-ly-hoc-sinh',
    tmhs:'/them-moi-hoc-sinh',
    qlgv:'/quan-ly-giao-vien',
    edit:'/edit',
    qlkv:'/quan-ly-khoa-vien',
    tm:'/them-moi',
    editlh:'/lophoc/:id',
    qln:'/quan-ly-nganh',
    editkv:'/chinh-sua-nganh',
    tmn:'/them-moi-nganh',
    qlk:'/quan-ly-khoa',
    tmk:'/them-moi-khoa',
    editkhoa:'/editkhoa',
    tmgv:'/them-moi-giao-vien',
    ttvc:'/thong-tin-vien-chuc',
    ttmh:'/thong-tin-mon-hoc',
    tmmh:'/them-moi-mon-hoc',
    editmonhoc:'/chinh-sua-mon-hoc',
    dsph:'/danh-sach-phu-huynh',
    tmph:'/them-moi-phu-huynh',
    dstk:'/danh-sach-tai-khoan',
    qlkhht:'/quan-ly-ke-hoach-hoc-tap',
    tmlh:'/them-moi-lich-hoc',
    dshstm:'/danh-sach-theo-mon',
    dhs:'/danh-sach-hoc-sinh',
    bdhs:'/bang-diem-hoc-sinh',
    editgv:'/chinh-sua-thong-tin-giao-vien',
    lgd: '/lich-giang-day',
    dslcv:'/danh-sach-lop-co-van',
    dshstl:'/danh-sach-hoc-sinh-theo-lop',
    ndhs:'/nhap-diem-hoc-sinh/:id',
    ctdt:'/chuong-trinh-dao-tao',
    khht:'/ke-hoach-hoc-tap',
    khhths:'/ke-hoach-hoc-tap-hoc-sinh',
    lhhs:'/lich-hoc-hoc-sinh',
    dsn:'/danh-sach-nganh',
    dslgd:'/danh-sach-lich-giang-day',
    dslvp:'/danh-sach-loi-vi-pham/:id',
    diemrenluyen:'/diem-ren-luyen',
    ctlvp:'/chi-tiet-loi-vi-pham',
    dslh:'/danh-sach-lop-hoc',
    tkbgv:'/thoi-khoa-bieu-giao-vien',
    lgdgv:'/lich-giang-day-giao-vien',
    lvp: '/loi-vi-pham',
    in: '/in-danh-sach',
};

export default routesAdmin;
